import:
  - imports-level-3
  - imports-level-3a

vars:
  region: us-east-2
  environment: ue2

terraform:
  vars:
    test: true

  backend_type: s3 # s3, remote, vault, etc.
  backend:
    s3:
      encrypt: true
      bucket: "eg-ue2-root-tfstate"
      key: "terraform.tfstate"
      dynamodb_table: "eg-ue2-root-tfstate-lock"
      role_arn: "arn:aws:iam::xxxxxxxxxxxx:role/eg-gbl-root-terraform"
      acl: "bucket-owner-full-control"
      region: "us-east-2"
    remote: {}
    vault: {}

helmfile:
  vars: {}
